spring:
  application:
    name: rqueue-rabbitmq-example
  
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    connection-timeout: 15000
    listener:
      simple:
        acknowledge-mode: auto
        concurrency: 1
        max-concurrency: 10
        prefetch: 1
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 1000
          max-interval: 10000
          multiplier: 2

rqueue:
  enabled: true
  key-prefix: "__rq::"
  job-enabled: true
  cluster-mode: false
  message-durability: 10080
  message-durability-in-terminal-state: 1800
  retry-per-poll: 1
  system-mode: BOTH
  reactive-enabled: false
  latest-version-check-enabled: true

logging:
  level:
    com.github.sonus21.rqueue: DEBUG
    org.springframework.amqp: DEBUG
    org.springframework.rabbit: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always